version: '3'

services:
  container1:
    build: ../task5
    container_name: container1
  nginx:
    image: nginx
    container_name: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - container1
    ports:
      - "80:8080"
